# Render Blueprint: MERN stack (server + client)

services:
  # Express/Node backend (Web Service)
  - type: web
    name: mern-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18

  # React frontend (Static Site)
  - type: static
    name: mern-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: build
    autoDeploy: true

